config/routes.rb
MicroCRM::Application.routes.draw do

  resources :monits

  resources :permissions

  resources :roles

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'
  match '/signin', to:  'sessions#new'
  match '/signout', to:  'sessions#destroy'
  match "/auth/:provider/callback", :to => 'sessions#create'   

   root :to => 'home#index'

end

app/models/monit.rb
class Monit < ActiveRecord::Base
  attr_accessible :desc, :name, :script, :state

 def self.exeue_script
      p "--------"
      p Monit.count
       Monit.all.each do |monit|

         p monit.script

         temp = Monit.find_by_sql(monit.script)
         p temp[0]
         monit.desc= temp.to_s



         monit.save!


       end
  end
end

app/controllers/monits_controller.rb
class MonitsController < ApplicationController
  # GET /monits
  # GET /monits.json
  def index
    @monits = Monit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @monits }
    end
  end

  # GET /monits/1
  # GET /monits/1.json
  def show
    @monit = Monit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @monit }
    end
  end

  # GET /monits/new
  # GET /monits/new.json
  def new
    @monit = Monit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @monit }
    end
  end

  # GET /monits/1/edit
  def edit
    @monit = Monit.find(params[:id])
  end

  # POST /monits
  # POST /monits.json
  def create
    @monit = Monit.new(params[:monit])

    respond_to do |format|
      if @monit.save
        format.html { redirect_to @monit, notice: 'Monit was successfully created.' }
        format.json { render json: @monit, status: :created, location: @monit }
      else
        format.html { render action: "new" }
        format.json { render json: @monit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /monits/1
  # PUT /monits/1.json
  def update
    @monit = Monit.find(params[:id])

    respond_to do |format|
      if @monit.update_attributes(params[:monit])
        format.html { redirect_to @monit, notice: 'Monit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @monit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monits/1
  # DELETE /monits/1.json
  def destroy
    @monit = Monit.find(params[:id])
    @monit.destroy

    respond_to do |format|
      format.html { redirect_to monits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/monits_helper.rb
module MonitsHelper
end

app/views/monits/_form.html.erb
<%= form_for(@monit) do |f| %>
  <% if @monit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monit.errors.count, "error") %> prohibited this monit from being saved:</h2>

      <ul>
      <% @monit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :script %><br />
    <%= f.text_field :script %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monits/edit.html.erb
<h1>Editing monit</h1>

<%= render 'form' %>

<%= link_to 'Show', @monit %> |
<%= link_to 'Back', monits_path %>

app/views/monits/index.html.erb
<h1>Listing monits</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Script</th>
    <th>Desc</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @monits.each do |monit| %>
  <tr>
    <td><%= monit.name %></td>
    <td><%= monit.script %></td>
    <td><%= monit.desc %></td>
    <td><%= monit.state %></td>
    <td><%= link_to 'Show', monit %></td>
    <td><%= link_to 'Edit', edit_monit_path(monit) %></td>
    <td><%= link_to 'Destroy', monit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Monit', new_monit_path %>

app/views/monits/new.html.erb
<h1>New monit</h1>

<%= render 'form' %>

<%= link_to 'Back', monits_path %>

app/views/monits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @monit.name %>
</p>

<p>
  <b>Script:</b>
  <%= @monit.script %>
</p>

<p>
  <b>Desc:</b>
  <%= @monit.desc %>
</p>

<p>
  <b>State:</b>
  <%= @monit.state %>
</p>


<%= link_to 'Edit', edit_monit_path(@monit) %> |
<%= link_to 'Back', monits_path %>