config/routes.rb
MicroCRM::Application.routes.draw do

  resources :monits

  resources :permissions

  resources :roles

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'
  match '/signin', to:  'sessions#new'
  match '/signout', to:  'sessions#destroy'
  match "/auth/:provider/callback", :to => 'sessions#create'   

   root :to => 'home#index'

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  attr_accessible :action, :description, :name, :subject_class
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  # GET /permissions
  # GET /permissions.json
  #skip_authorization_check :only => [:index]
  authorize_resource

  before_filter :find_permission, :only => [:show, :edit, :update, :destroy]

  def index
    @permissions = Permission.paginate(:page => params[:page])
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show

  end

  # GET /permissions/new
  # GET /permissions/new.json
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit

  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(params[:permission])


    if @permission.save
      redirect_to @permission, notice: 'Permission was successfully created.'
    else
      render action: "new"
    end

  end

  # PUT /permissions/1
  # PUT /permissions/1.json
  def update
    if @permission.update_attributes(params[:permission])
      redirect_to @permission, notice: 'Permission was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy

    @permission.destroy
    redirect_to permissions_url

  end

  protected
  def find_permission
    @permission = Permission.find(params[:id])
  end


end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= form_for(@permission) do |f| %>
  <% if @permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% @permission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subject_class %><br />
    <%= f.text_field :subject_class %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing permission</h1>

<%= render 'form' %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<h1>Listing permissions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Subject class</th>
    <th>Action</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @permissions.each do |permission| %>
  <tr>
    <td><%= permission.name %></td>
    <td><%= permission.subject_class %></td>
    <td><%= permission.action %></td>
    <td><%= permission.description %></td>
    <td><%= link_to 'Show', permission %></td>
    <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
    <td><%= link_to 'Destroy', permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Permission', new_permission_path %>

app/views/permissions/new.html.erb
<h1>New permission</h1>

<%= render 'form' %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @permission.name %>
</p>

<p>
  <b>Subject class:</b>
  <%= @permission.subject_class %>
</p>

<p>
  <b>Action:</b>
  <%= @permission.action %>
</p>

<p>
  <b>Description:</b>
  <%= @permission.description %>
</p>


<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>