config/routes.rb
MicroCRM::Application.routes.draw do

  resources :monits

  resources :permissions

  resources :roles

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'
  match '/signin', to:  'sessions#new'
  match '/signout', to:  'sessions#destroy'
  match "/auth/:provider/callback", :to => 'sessions#create'   

   root :to => 'home#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :desc, :name, :permission, :state
  has_many :users


  def permissions
    temp = self.permission.split(",") || []
    Permission.find(temp)
  end  

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  authorize_resource
  #load_and_authorize_resource 
  before_filter :find_role, :only  => [:show, :edit, :update, :destroy]
  def index
    @roles = Role.paginate(:page  =>  params[:page])
  end

  # GET /roles/1
  # GET /roles/1.json
  def show


  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new


  end

  # GET /roles/1/edit
  def edit

  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

      if @role.save
        redirect_to @role, notice: 'Role was successfully created.'
      else
         render action: "new"
      end

  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update


      if @role.update_attributes(params[:role])
        redirect_to @role, notice: 'Role was successfully updated.'

      else
         render action: "edit"
      end

  end


  def destroy

    @role.destroy
    redirect_to roles_url

  end
  protected
  def find_role
      @role = Role.find(params[:id])
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :permission %><br />
    <%= f.text_field :permission %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Permission</th>
    <th>Desc</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= role.permission %></td>
    <td><%= role.desc %></td>
    <td><%= role.state %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= will_paginate(@roles, :renderer => WillPaginate::ActionView::LinkRenderer, :previous_label => "<<上一页",
                  :next_label => "下一页>>", :class => "pagination") %>
<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>

<p>
  <b>Permission:</b>
  <%= @role.permission %>
</p>

<p>
  <b>Desc:</b>
  <%= @role.desc %>
</p>

<p>
  <b>State:</b>
  <%= @role.state %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>