config/routes.rb
MicroCRM::Application.routes.draw do

  resources :monits

  resources :permissions

  resources :roles

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'
  match '/signin', to:  'sessions#new'
  match '/signout', to:  'sessions#destroy'
  match "/auth/:provider/callback", :to => 'sessions#create'   

   root :to => 'home#index'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "MicroCRM", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", "#"  %></li>
          <% if signed_in? %>
              <li><%= link_to current_user.name, '#' %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroCRM</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

</head>
<body>
<%= render  'layouts/header' %>

<div class="container">

  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

    <%= yield %>

  <%= debug(params) if Rails.env.development? %>
</div>


</body>
</html>